ktor:
    application:
        modules:
            - com.tournament.ApplicationKt.module
    deployment:
        port: 9090
    datasource:
        url: "jdbc:h2:mem:tournament;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;"
        driverClassName: "org.h2.Driver"
        username: "sa"
        password: ""